echo sonar.projectKey=Tuning > sonar-project.properties
echo sonar.projectName=Tuning >> sonar-project.properties
echo sonar.sources=. >> sonar-project.properties
echo sonar.exclusions=**/tests/**,**/static/** >> sonar-project.properties
echo sonar.python.version=3.13.1 >> sonar-project.properties
echo sonar.sourceEncoding=UTF-8 >> sonar-project.properties
echo sonar.host.url=http://localhost:9000 >> sonar-project.properties
echo sonar.login=sqb_3....dfgpqkv >> sonar-project.properties


"""
Se hacen estos cambios por seguridad!
"""
